Algoritmo "exibirNome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   :
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Girlany
// Data atual  : 11/06/2022
Var
// Seção de Declarações das variáveis 
Nome:  Caracter
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva ("Digite o nome: ")
    Leia (Nome)
Escreva ("O nome digitado é: ", Nome)

Fimalgoritmo